// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8sNDIvabQ2ozEYBzNeO4Yw40qlKqGJv0',
    appId: '1:502922810197:web:672e87a05600a375c0d5dc',
    messagingSenderId: '502922810197',
    projectId: 'login-auth-10b90',
    authDomain: 'login-auth-10b90.firebaseapp.com',
    storageBucket: 'login-auth-10b90.firebasestorage.app',
    measurementId: 'G-MV31TV5878',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_pbDqrh4RLtgZKQLHWeEgHfcl0912pdo',
    appId: '1:502922810197:android:c3d33cdaab541935c0d5dc',
    messagingSenderId: '502922810197',
    projectId: 'login-auth-10b90',
    storageBucket: 'login-auth-10b90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnrh1W0Oj86sa7Nb2AL92dT2Xvf9OORAM',
    appId: '1:502922810197:ios:ee18c423050489efc0d5dc',
    messagingSenderId: '502922810197',
    projectId: 'login-auth-10b90',
    storageBucket: 'login-auth-10b90.firebasestorage.app',
    iosClientId: '502922810197-vs2cens8duqnf9kmsp38q1b1liutmd9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.bullStation',
  );
}
